version: "3.7"
services:
  php-deep-type:
    container_name: php-deep-type
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
      args:
        USER_ID: ${USER_ID}
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
